# Generated by Django 3.0.5 on 2020-04-26 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('username', models.TextField(default='')),
                ('fullname', models.TextField(default='')),
                ('img_url', models.TextField(default='/home/HACKDAY/portfolio/static/images/icons/user.png')),
                ('date_of_register', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('username', models.TextField(default='')),
                ('fullname', models.TextField(default='')),
                ('img_url', models.TextField(default='/home/HACKDAY/portfolio/static/images/icons/user.png')),
                ('medcard_url', models.TextField(default='/home/HACKDAY/portfolio/static/images/icons/camera.png')),
                ('university_course', models.IntegerField(null=True)),
                ('specialty', models.TextField(default='')),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_register', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.TextField(default='')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.City')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img_url', models.TextField(default='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University'),
        ),
    ]
