# Generated by Django 3.0.5 on 2020-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='achivements',
            field=models.ManyToManyField(blank=True, null=True, related_name='achivements', to='main.Achivement'),
        ),
        migrations.AlterField(
            model_name='student',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='main.View'),
        ),
    ]
