# Generated by Django 3.0.5 on 2020-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
