# Generated by Django 3.0.5 on 2020-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200426_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivement',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='request',
            name='owner',
        ),
        migrations.AddField(
            model_name='student',
            name='achivements',
            field=models.ManyToManyField(null=True, to='main.Achivement'),
        ),
        migrations.AddField(
            model_name='student',
            name='requests',
            field=models.ManyToManyField(null=True, to='main.Request'),
        ),
    ]
