# Generated by Django 3.0.5 on 2020-05-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vacancy_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('vacancy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Vacancy')),
            ],
        ),
    ]
