# Generated by Django 3.0.5 on 2020-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200427_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='img_url',
            field=models.TextField(default='/static/images/icons/user.png'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img_url',
            field=models.TextField(default='/static/images/icons/user.png'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medcard_url',
            field=models.TextField(default='/static/images/icons/camera.png'),
        ),
    ]
