# Generated by Django 3.0.5 on 2020-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_applied_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.ManyToManyField(blank=True, to='main.View'),
        ),
    ]
