# Generated by Django 3.0.5 on 2020-04-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200427_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='achivements',
            field=models.ManyToManyField(blank=True, null=True, to='main.Achivement'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='requests',
            field=models.ManyToManyField(blank=True, null=True, to='main.Request'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.University'),
        ),
    ]
