# Generated by Django 3.0.5 on 2020-05-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200504_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_vacancy',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
