# Generated by Django 3.0.5 on 2020-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200427_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_course',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
