# Generated by Django 3.0.5 on 2020-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200427_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='vk',
            field=models.TextField(default=''),
        ),
    ]
