# Generated by Django 3.0.5 on 2020-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200427_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
