# Generated by Django 3.0.5 on 2020-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_request_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
