# Generated by Django 3.0.5 on 2020-04-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medcard_url',
            field=models.TextField(default=''),
        ),
    ]
