# Generated by Django 3.0.5 on 2020-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200428_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_searching_work',
            field=models.BooleanField(default=True),
        ),
    ]
