# Generated by Django 3.0.5 on 2020-04-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_is_searching_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.City'),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
