# Generated by Django 3.0.5 on 2020-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_is_searching_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='telegram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='vk',
            field=models.TextField(default=''),
        ),
    ]
