# Generated by Django 3.0.5 on 2020-04-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200429_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.City'),
        ),
    ]
