# Generated by Django 3.0.5 on 2020-04-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200429_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='city',
        ),
    ]
