# Generated by Django 3.0.5 on 2020-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_employer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='telegram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='vk',
            field=models.TextField(default=''),
        ),
    ]
